# Generated by Django 5.2.1 on 2025-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
