# Generated by Django 5.2.1 on 2025-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_transaction_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[("domestik", "Domestik"), ("asing", "Asing")],
                        max_length=10,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[("adult", "Adult"), ("child", "Child")], max_length=5
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipe Tiket",
                "verbose_name_plural": "Semua Tipe Tiket",
                "unique_together": {("nationality", "age_group")},
            },
        ),
    ]
