# Generated by Django 5.2.1 on 2025-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Topik utama dari item pengetahuan ini (e.g., 'Lokasi Parkir Utama')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        help_text="Kata kunci yang relevan untuk memicu topik ini, dipisahkan koma (e.g., parkir, mobil, motor, tempat parkir)"
                    ),
                ),
                (
                    "information",
                    models.TextField(
                        help_text="Informasi detail yang akan diberikan sebagai jawaban oleh chatbot."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Pengetahuan",
                "verbose_name_plural": "Item-item Pengetahuan",
                "ordering": ["topic"],
            },
        ),
    ]
